create extension if not exists pgcrypto;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (char_length(event_name) between 1 and 50),
  category text not null check (char_length(category) between 1 and 50),
  label text not null check (char_length(label) between 1 and 120),
  project_id text check (project_id is null or char_length(project_id) <= 100),
  path text not null check (char_length(path) between 1 and 500),
  target_url text check (target_url is null or char_length(target_url) <= 500),
  session_id uuid not null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_project_idx on public.analytics_events (project_id, created_at desc) where project_id is not null;
create index if not exists analytics_events_category_idx on public.analytics_events (category, created_at desc);

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from anon, authenticated;

create table if not exists public.analytics_admins (
  email text primary key check (email = lower(trim(email))),
  created_at timestamptz not null default now()
);

alter table public.analytics_admins enable row level security;
revoke all on table public.analytics_admins from anon, authenticated;

create or replace function public.record_analytics_event(
  p_event_name text,
  p_category text,
  p_label text,
  p_project_id text default null,
  p_path text default '/',
  p_target_url text default null,
  p_session_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_session_id is null
    or char_length(trim(coalesce(p_event_name, ''))) not between 1 and 50
    or char_length(trim(coalesce(p_category, ''))) not between 1 and 50
    or char_length(trim(coalesce(p_label, ''))) not between 1 and 120
    or char_length(trim(coalesce(p_path, ''))) not between 1 and 500
  then
    raise exception 'Invalid analytics event';
  end if;

  if (
    select count(*)
    from public.analytics_events
    where session_id = p_session_id
      and created_at > now() - interval '1 minute'
  ) >= 120 then
    return;
  end if;

  insert into public.analytics_events (event_name, category, label, project_id, path, target_url, session_id)
  values (
    trim(p_event_name),
    trim(p_category),
    trim(p_label),
    nullif(left(trim(coalesce(p_project_id, '')), 100), ''),
    left(trim(p_path), 500),
    nullif(left(trim(coalesce(p_target_url, '')), 500), ''),
    p_session_id
  );
end;
$$;

revoke all on function public.record_analytics_event(text, text, text, text, text, text, uuid) from public;
grant execute on function public.record_analytics_event(text, text, text, text, text, text, uuid) to anon, authenticated;

create or replace function public.get_analytics_summary(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  safe_days integer := least(greatest(coalesce(p_days, 30), 1), 365);
begin
  if not (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    or coalesce(auth.jwt() -> 'user_metadata' ->> 'role', '') = 'admin'
    or exists (
      select 1 from public.analytics_admins
      where email = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
  ) then
    raise exception 'Admin access required';
  end if;

  with filtered as (
    select * from public.analytics_events
    where created_at >= now() - make_interval(days => safe_days)
  ),
  totals as (
    select
      count(*)::integer as total_events,
      count(*) filter (where event_name = 'click')::integer as total_clicks,
      count(distinct session_id)::integer as unique_sessions,
      count(*) filter (where category = 'project')::integer as project_clicks
    from filtered
  ),
  buttons as (
    select label, count(*)::integer as clicks
    from filtered
    where event_name = 'click' and category = 'button'
    group by label
    order by clicks desc, label
    limit 12
  ),
  projects as (
    select project_id, max(label) as label, count(*)::integer as clicks
    from filtered
    where event_name = 'click' and category = 'project' and project_id is not null
    group by project_id
    order by clicks desc, project_id
    limit 12
  ),
  pages as (
    select path, count(*)::integer as views
    from filtered
    where event_name = 'page_view'
    group by path
    order by views desc, path
    limit 12
  ),
  days as (
    select series::date as day
    from generate_series(current_date - (safe_days - 1), current_date, interval '1 day') series
  ),
  daily_counts as (
    select created_at::date as day, count(*)::integer as events
    from filtered
    group by created_at::date
  )
  select jsonb_build_object(
    'total_events', totals.total_events,
    'total_clicks', totals.total_clicks,
    'unique_sessions', totals.unique_sessions,
    'project_clicks', totals.project_clicks,
    'top_buttons', coalesce((select jsonb_agg(to_jsonb(buttons)) from buttons), '[]'::jsonb),
    'top_projects', coalesce((select jsonb_agg(to_jsonb(projects)) from projects), '[]'::jsonb),
    'top_pages', coalesce((select jsonb_agg(to_jsonb(pages)) from pages), '[]'::jsonb),
    'daily', coalesce((select jsonb_agg(jsonb_build_object('day', days.day, 'events', coalesce(daily_counts.events, 0)) order by days.day) from days left join daily_counts using (day)), '[]'::jsonb)
  ) into result
  from totals;

  return result;
end;
$$;

revoke all on function public.get_analytics_summary(integer) from public;
grant execute on function public.get_analytics_summary(integer) to authenticated;

update public.projects set status = 'Launched' where status is distinct from 'Launched';
